### ISSUE TITLE
File naming mistake (VLink.vue instead Vlink.vue)

### ISSUE THREAD

**Issue by NadhirBoukhenifra** [codeitlikemiley/vuetified#2]
Hi,
after running this command:
`npm run watch
`
i get error:
```
 ERROR  Failed to compile with 1 errors                                                      16:12:37

 error  in ./resources/assets/js/components/VLink.vue

Module build failed: Error: ENOENT: no such file or directory, open '/home/nadhir/p/Vuetified/resources/assets/js/components/VLink.vue'

```
just i fixed it by renaming this file from:
`/resources/assets/js/components/Vlink.vue
`to
`/resources/assets/js/components/VLink.vue
`

**Comment by aruxek** [comment]
Try  change in the file /resources/assets/js/components/LeftSideBar.vue file on line 35

Import VLink from '../components/VLink.vue'

to

Import VLink from '../components/Vlink.vue'

**Comment by codeitlikemiley** [comment]
thanks ive already change it, but as of now, im on the process of making this a preset at the same time a serviceprovider...

so we might expect this to be a package...
which would consume laravel preset commands
and laravel autopackage discovery...

i just have time this day, since im doing a lot lately, developing other stuff...
but hopefully i can launch this as a package soon

**Comment by codeitlikemiley** [comment]
already push this to the update
